# Assignment 4 
### Name : Priya Ranjan Kumar
### Roll No : 231030041

In [13]:
# Loading packages 
import numpy as np
import pandas as pd


# Question 1

In [44]:
#(a)
# Define the dimensions of the array
width = 72
height = 72
frames = 150

# Create an 3D array
df = np.zeros((width, height, frames))

# Fill the values of the array
for i in range(frames):
    df[:, :, i] = i

# Show the output of data[:, :, 4]
print(df[:, :, 4])


[[4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 ...
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]]


In [45]:
#(b)

background = np.mean(d[:, :, :5], axis=2)

# Show the output 
print(background)
print("Shape of Background Frame:", background.shape)


[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
Shape of Background Frame: (72, 72)


In [47]:
#(c)
# Replicate the frame
background_rp = np.tile(background[:,:,np.newaxis],(1,1,num_frames))

# Subtract the replicated background from each frame in data
noise_e = data - background_rp

# Show the output of noise_elim[:, :, 0], noise_elim[:, :, 5], and its shape
print("noise_e[:,:,0]:")
print(noise_e[:,:,0])
print("noise_e[:,:,5]:")
print(noise_e[:,:,5])

noise_e[:,:,0]:
[[-2. -2. -2. ... -2. -2. -2.]
 [-2. -2. -2. ... -2. -2. -2.]
 [-2. -2. -2. ... -2. -2. -2.]
 ...
 [-2. -2. -2. ... -2. -2. -2.]
 [-2. -2. -2. ... -2. -2. -2.]
 [-2. -2. -2. ... -2. -2. -2.]]
noise_e[:,:,5]:
[[3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]]


In [51]:
#(d)
# Calculate the average temperature
avg_temperature = np.mean(data, axis=(0, 1))

# Show the output of the array avg_temperate
print("average_temperature:")
print(avg_temperature)

average_temperature:
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149.]


In [52]:
#(e)
# Find position of the maximum average temperature
max_frame_i = np.argmax(avg_temperature)

max_frame_c = data[:, :, max_frame_i]

# Show the index of the frame with maximum average temperature
print("Index of Frame with Maximum Average Temperature:", max_frame_i)

# Show the frame with maximum average temperature
print("Frame with Maximum Average Temperature (data[:, :, max_frame]):")
print(max_frame_c)


Index of Frame with Maximum Average Temperature: 149
Frame with Maximum Average Temperature (data[:, :, max_frame]):
[[149. 149. 149. ... 149. 149. 149.]
 [149. 149. 149. ... 149. 149. 149.]
 [149. 149. 149. ... 149. 149. 149.]
 ...
 [149. 149. 149. ... 149. 149. 149.]
 [149. 149. 149. ... 149. 149. 149.]
 [149. 149. 149. ... 149. 149. 149.]]


In [53]:
#f-i
# Create shifted versions of the data array for (i-1, j), (i, j-1), (i+1, j), (i, j+1), and (i, j)
data_in = np.roll(noise_elim, shift=(-1, 0, 0), axis=(0, 1, 2))
data_ip = np.roll(noise_elim, shift=(1, 0, 0), axis=(0, 1, 2))
data_jn = np.roll(noise_elim, shift=(0, -1, 0), axis=(0, 1, 2))
data_jp = np.roll(noise_elim, shift=(0, 1, 0), axis=(0, 1, 2))
data_ij = np.roll(noise_elim, shift=(0, 0, 1), axis=(0, 1, 2))

# Display the 5th frame of each of these 5 arrays
print("5th frame of data_in:\n",data_in[:, :, 4])


print("5th frame of data_ip:\n",data_ip[:, :, 4])


print("5th frame of data_jn:\n",data_jn[:, :, 4])


print("5th frame of data_jp:\n",data_jp[:, :, 4])


print("5th frame of data_ij:\n",data_ij[:, :, 4])


5th frame of data_in:
 [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
5th frame of data_ip:
 [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
5th frame of data_jn:
 [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
5th frame of data_jp:
 [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
5th frame of data_ij:
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [54]:
#(f-ii)
# Calculate the average of the five arrays to create a new image sequence
new_image_sequence = (data_in + data_ip + data_jn + data_jp + data_ij) / 5

# Find the hottest frame index (index with the maximum average temperature)
avg_temp = np.mean(new_image_sequence, axis=(0, 1))  # Calculate average temperature for each frame
hottest_frame_index = np.argmax(avg_temp)  # Find the index of the hottest frame

print(new_image_sequence)
print("Shape of the new image sequence:", new_image_sequence.shape)
print("Hottest frame index:", hottest_frame_index)

[[[ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  ...
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]]

 [[ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  ...
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]]

 [[ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  ...
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]]

 ...

 [[ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146.8]
  ...
  [ 27.8  -1.2  -0.2 ... 144.8 145.8 146

# Question 2 

In [55]:
#a
event = pd.read_csv('event_2019_nyc.csv')

# Output the no. of events present in the dataset
n_events = len(event)
print("Number of events :", n_events)


Number of events : 27808


In [56]:
#(b)
# Get unique states and their event counts
unq_states = event['State'].unique()
state_event_count = event['State'].value_counts()

# Output the names of unique states
print("Unique States in the Dataset:")
for state in unq_states:
    print(state)

# Output the number of events reported in each state
print("\nNumber of Events Reported in Each State:")
for state, count in state_event_counts.items():
    print(f"{state}: {count} events")


Unique States in the Dataset:
NJ
NY
PA
CT

Number of Events Reported in Each State:
NY: 19527 events
NJ: 8253 events
CT: 26 events
PA: 2 events


In [43]:
#(c)
# Read the CSV file 
event = pd.read_csv('event_2019_nyc.csv')

# Convert the "Create Time" and "Close Time" columns to datetime format
event['Create Time'] = pd.to_datetime(event['Create Time'])
event['Close Time'] = pd.to_datetime(event['Close Time'])

# Calculate the "Event Duration" in hours
event['Event Duration'] = (event['Close Time'] - event['Create Time']).dt.total_seconds() / 3600

# output
print(event[['Create Time', 'Close Time', 'Event Duration']].head())


          Create Time          Close Time  Event Duration
0 2019-01-01 10:28:48 2019-01-01 10:31:45        0.049167
1 2019-01-01 10:47:49 2019-01-01 11:09:05        0.354444
2 2019-01-01 13:07:46 2019-01-01 14:02:49        0.917500
3 2019-01-01 14:50:46 2019-01-01 16:32:56        1.702778
4 2019-01-01 17:11:46 2019-01-01 18:25:44        1.232778


In [58]:
#(d)
# Convert the "Create Time" 
event['Create Time'] = pd.to_datetime(event['Create Time'])

# Extract the month and save as new column "Month"
event['Month'] = event['Create Time'].dt.month

# Calculate the number of events in each month
monthlyevent = event['Month'].value_counts().sort_index()

# Output the number of events in each month
print(monthlyevent)

# Find the month with the maximum number of events
max_month = monthly_event_counts.idxmax()
max_event_count = monthlyevent.max()
print("\nMonth with Maxm no. of event:")
print(f"Month {max_month} with {max_event_count} events")


1    4690
2    3146
3    4217
7    5312
8    5284
9    5159
Name: Month, dtype: int64

Month with Maxm no. of event:
Month 7 with 5312 events
